// Header file generated by paddle/phi/CMakeLists.txt for external users,
// DO NOT edit or include it within paddle.

#pragma once

#include "paddle/phi/backends/all_context.h"
#include "paddle/phi/backends/c_comm_lib.h"
#include "paddle/phi/backends/callback_manager.h"
#include "paddle/phi/backends/device_base.h"
#include "paddle/phi/backends/device_ext.h"
#include "paddle/phi/backends/device_guard.h"
#include "paddle/phi/backends/device_manager.h"
#include "paddle/phi/backends/event.h"
#include "paddle/phi/backends/stream.h"
