# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fleet_executor_desc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fleet_executor_desc.proto',
  package='paddle.distributed',
  syntax='proto2',
  serialized_pb=_b('\n\x19\x66leet_executor_desc.proto\x12\x12paddle.distributed\")\n\x08RankInfo\x12\x0c\n\x04rank\x18\x01 \x02(\x03\x12\x0f\n\x07ip_port\x18\x02 \x02(\t\"\\\n\x11\x46leetExecutorDesc\x12\x13\n\x08\x63ur_rank\x18\x01 \x01(\x03:\x01\x30\x12\x32\n\x0c\x63luster_info\x18\x02 \x03(\x0b\x32\x1c.paddle.distributed.RankInfo')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RANKINFO = _descriptor.Descriptor(
  name='RankInfo',
  full_name='paddle.distributed.RankInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rank', full_name='paddle.distributed.RankInfo.rank', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip_port', full_name='paddle.distributed.RankInfo.ip_port', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=90,
)


_FLEETEXECUTORDESC = _descriptor.Descriptor(
  name='FleetExecutorDesc',
  full_name='paddle.distributed.FleetExecutorDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cur_rank', full_name='paddle.distributed.FleetExecutorDesc.cur_rank', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cluster_info', full_name='paddle.distributed.FleetExecutorDesc.cluster_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=184,
)

_FLEETEXECUTORDESC.fields_by_name['cluster_info'].message_type = _RANKINFO
DESCRIPTOR.message_types_by_name['RankInfo'] = _RANKINFO
DESCRIPTOR.message_types_by_name['FleetExecutorDesc'] = _FLEETEXECUTORDESC

RankInfo = _reflection.GeneratedProtocolMessageType('RankInfo', (_message.Message,), dict(
  DESCRIPTOR = _RANKINFO,
  __module__ = 'fleet_executor_desc_pb2'
  # @@protoc_insertion_point(class_scope:paddle.distributed.RankInfo)
  ))
_sym_db.RegisterMessage(RankInfo)

FleetExecutorDesc = _reflection.GeneratedProtocolMessageType('FleetExecutorDesc', (_message.Message,), dict(
  DESCRIPTOR = _FLEETEXECUTORDESC,
  __module__ = 'fleet_executor_desc_pb2'
  # @@protoc_insertion_point(class_scope:paddle.distributed.FleetExecutorDesc)
  ))
_sym_db.RegisterMessage(FleetExecutorDesc)


# @@protoc_insertion_point(module_scope)
